### ISSUE TITLE
Feature Request: Add to connection Listener

### ISSUE THREAD

**Issue by mikebell90** [box/box-java-sdk#103]
A listener with an interface like

public void aboutToRefresh();
public void refreshSuccess(String accessToken, String refreshToken, Long expirationTime);
public void refreshFailure();

would delineate state better. Moreover, it would allow one to update their persistance with the new token info once the update occurs.

**Comment by gcurtis** [comment]
I like this idea.

In #104 I'm thinking of making `onRefresh()` pass a state string instead of the access token, refresh token, etc. separately. I'm not entirely sure about the `aboutToRefresh()` method though. Are there situations where knowing that a refresh is about to happen is useful?

So far this is how I envision the new interface:

```java
public void onRefresh(String state);
public void onError(Exception e);
```

**Comment by mikebell90** [comment]
If I read #104 correctly, you are passing an opaque json serialization. That works great for you, but couples an assumption of format for anyone needing to decode this (to update their database). That strikes me as problematic. I did not suggest pass ApiConnection btw, because I thought the accidental mutation would be undesirable. Hence the bare Strings.

aboutToRefresh() - eh I don't feel too strongly about it. It's sometimes nice for debugging purpose to log this. (from my experience in writing a similar api). That's mostly the only reason actually.

**Comment by gcurtis** [comment]
The work for this will be done as part of #104.
