### ISSUE TITLE
Downloading Trash files and folders

### ISSUE THREAD

**Issue by mgrytsai** [box/box-java-sdk#1049]
### Discussed in https://github.com/box/box-java-sdk/discussions/1028

<div type='discussions-op-text'>

<sup>Originally posted by **samrajcse** March  7, 2022</sup>
Hi Team,
I am using JAVA Box SDK. I want to iterate all the files and folders in the trash with pagiantion. I don't want all the files in the single call. How can we do it?

In the sample code, pagination is not there.  I need to download the files inside the folders inside the trash as well.</div>

**Comment by antusus** [comment]
The Box [Java SDK 3.4.0 ](https://github.com/box/box-java-sdk/releases/tag/v3.4.0)now supports pagination while getting the trash items: https://github.com/box/box-java-sdk/blob/main/doc/trash.md#get-trashed-items.

You have to restore file/folder from trash in order to download it:

```java
var trash = new BoxTrash(api);
trash.items(SortParameters.none(), PagingParameters.marker(500)).forEach(i -> {
    if(i.getType().equals("file")) {
        var restoreFile = trash.restoreFile(i.getID());
        var boxFile = new BoxFile(api, restoreFile.getID());
        try {
            boxFile.download(Files.newOutputStream(new File("/my/path/" + i.getName()).toPath()));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
});
```
Hopefully this solves your problem. If needed please reopen the issue.
