### ISSUE TITLE
Box API exception Couldn't connect to the Box API due to a network error

### ISSUE THREAD

**Issue by rexbrothers** [box/box-java-sdk#1066]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [ ] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [ ] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [ ] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
We are seeing the following error for Box file upload and Box view APIs

message=BoxService Unavailable
exceptionMessage= Couldn't connect to Box API due to a network error.

![image](https://user-images.githubusercontent.com/5494395/175664216-e70b98f5-70be-4672-9be0-4e282db22dd7.png)

https://api.box.com/oauth2/token
 https://upload.box.com/api/2.0/files/content
https://api.box.com/2.0/files/905390495631
https://api.box.com/2.0/files/{fileId}

### Error Message, Including Stack Trace
![image](https://user-images.githubusercontent.com/5494395/175666736-ab00af1b-49f4-47b3-b5e7-7d87ec0f4640.png)

### Versions Used
Java SDK: 3.1.2
Java: 8

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @rexbrothers, thanks for reporting this issue we will try to help you with it.

But we have some question related to this issue:

1) Is this error occurs every time when you try to upload a file?
2) Have you notice same problem in other requests as well?
3) Which kind of authentication you are using here? Is it OAuth, JWT, CCG?
4) Are you using some proxy? Or maybe you have blocked some domains in your company?
5) Have you tried to upload a file by using curl or postman? What was the result?
6) Please try to upload a file by executing the curl command below, where you need to update 
three values:

`YOUR_TOKEN_HERE` 
`YOUR_FILE_NAME_HERE`
`PATH_TO_YOUR_FILE_HERE`

```
curl --location --request POST 'https://upload.box.com/api/2.0/files/content' \
--header 'Content-Type: multipart/form-data' \
--header 'Authorization: Bearer YOUR_TOKEN_HERE' \
--form 'attributes="{
  \"name\": \"YOUR_FILE_NAME_HERE.png\",
  \"parent\": {
    \"id\": \"0\"
  }
}"' \
--form 'file=@"/Users/PATH_TO_YOUR_FILE_HERE"'
```

Are you able to upload a file by using this command? Was was the result of this?

**Comment by rexbrothers** [comment]
Answers:

1.) This is an intermittent issue.
2.) The issue occurs intermittently for any of our box requests, for view, getting subfolder inside a folder.
GET https://api.box.com/2.0/folders/143128707847/items/?limit=1000&offset=0
GET https://api.box.com/2.0/files/905390495631
3.) We are using Oauth2 authentication. We acquire access token using https://api.box.com/oauth2/token.
4.) Will provide from our infrastructure team.
5.) We experience this error intermittently when using curl or Postman.
6.) We experience this error intermittently when using the provided curl.

**Comment by arjankowski** [comment]
@rexbrothers,

If you experience this error when using curl or postman like you mentioned, then this is not related to box java sdk itself,
as our sdks are only exposing the public Box API.

This is probably due to your network/proxy configuration, so please contact your admin to investigate it further.

**Comment by rexbrothers** [comment]
We are receiving following error.


![MicrosoftTeams-image (19)](https://user-images.githubusercontent.com/5494395/176009226-668282a4-15c4-4ede-9db0-b1bd087c18a2.png)

**Comment by rexbrothers** [comment]
We have used curl to access Box directly (without SDK) from our environment and receive no errors.

**Comment by arjankowski** [comment]
@rexbrothers,

Thanks for your logs, but there is so little information so let me ask you a few more questions to help us investigate this issue.

1) To be clear, did you use the example curl I gave? Has it always worked?

2) Can you please provide me your snippet of code which is causing the error you showed in the attached picture?

**Comment by rexbrothers** [comment]
1. The example curl has always worked.
2. 
![image](https://user-images.githubusercontent.com/5494395/176190068-da124a51-6439-4456-aec7-baafd097819d.png)

This error intermittently happens for all our Box requests File Upload, View, Search......

**Comment by arjankowski** [comment]
Hi @rexbrothers,
 
Unfortunately I'm still not able to reproduce this error by running the code similar to your.

1)
Are you sure that you are using OAuth authentication like you mentioned previously?
Because in your example you are using BoxDeveloperEditionAPIConnection which is using JWT.

2)
Your example seems to be OK, so I have another ask for you.
Can you download a source code of `box-java-sdk` from [here](https://github.com/box/box-java-sdk).

Then you can run an example **Main**`(/src/example/java/com/box/sdk/example/Main.java)` which is just iterating through folder items. 
But before run, please put your developer token to the field `DEVELOPER_TOKEN` 
which is on the top of this `Main.java` file.

What is **IMPORTANT** here, please run this example in the same network configuration
where this error occurs.

Please run this a dozen times, to see if an error occurs, and let me know about results.


3)
I was able to get this error `Couldn't connect to the Box API due to a network error` when I
changed baseURL to something wrong by using this method ` api.setBaseURL()` or when I hadn't internet access.

Do you think that this could be you case?

**Comment by rexbrothers** [comment]
We have concluded our issue is not SDK but an environment network issue.  I am closing the case. Thanks for all the help!

**Comment by rexbrothers** [comment]
We have concluded our issue is not SDK but an environment network issue. I am closing the case. Thanks for all the help!
