### ISSUE TITLE
Add support for web links

### ISSUE THREAD

**Issue by TLuthra** [box/box-java-sdk#124]
Add basic support for web links: https://box-content.readme.io/#web-link-object

**Comment by gcurtis** [comment]
Nice! It looks like we can finally stop ignoring web links in the SDK now that there's complete support for them.

Right now in `BoxItemIterator` [we're explicitly filtering them out](https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BoxItemIterator.java#L37-L46) since they couldn't cleanly inherit from `BoxItem`. But now it looks like they support the same operations as files/folders (copy, move, getting info, etc.).

This should be as simple as just inheriting from `BoxItem` and implementing all the necessary methods.

**Comment by tranquang9a1** [comment]
Is this finished or implementing ?
I cant find this document!

**Comment by Zeimyth** [comment]
Has there been any development for supporting web links yet? I don't see it in v2.1.1 of the SDK, so I wrote it myself with the intention of putting together a pull request. But I don't want to bother if it's already been done.
