### ISSUE TITLE
NPE in RequestInterceptor.onRequest() BoxAPIRequest.toString()

### ISSUE THREAD

**Issue by raj-jain** [box/box-java-sdk#133]
We implemented a simple RequestInterceptor to log outbound BoxAPIRequest objects. We call the toString() method on the request object. The SDK (v 1.0.0) throws an NPE (null pointer) at:

``` java
for (Map.Entry<String, List<String>> entry : this.requestProperties.entrySet()) { ... }
```

because this.requestProperties is null when the interceptor is invoked. This is because the interceptor callback is being called before the requestProperties have been set. A fix to move the interceptor invocation to after line # 372 where this.requestProperties is initialized works.

``` java
this.requestProperties = connection.getRequestProperties();
```

(move interceptor calling to around line # 374)

``` java
if (this.api != null) {
    RequestInterceptor interceptor = this.api.getRequestInterceptor();
    if (interceptor != null) {
        BoxAPIResponse response = interceptor.onRequest(this);
        if (response != null) {
            return response;
        }
    }
}
```

**Comment by gcurtis** [comment]
Thanks for pointing this out. The better behavior would definitely be to provide the headers to the request interceptor.

However, I don't think that invoking the interceptor later is a good idea, because then you incur the overhead of creating a new `HttpURLConnection` before you're certain that one will be needed (it's possible for the interceptor to return null and prevent the request from being sent entirely).

I think we should refactor `BoxAPIRequest` to store the relevant headers as private fields (outside of the `HttpURLConnection` instance) so that they can be provided to request interceptors. This should also solve the NPE in the `toString()` method.

**Comment by raj-jain** [comment]
Yes, I missed that the RequestInterceptor is intended to be used for simulating Box and simply moving its invocation to a later point, while works for my use case, is not a good solution.

There is already a list of headers in BoxAPIRequest but I guess you're saying that request properties of HttpURLConnection (such as Authorization, User-Agent etc.) should either be moved to that list or defined as first-class attributes of the BoxAPIRequest class.That sounds good. 

Actually, while we're at HttpURLConnection, I've one more problem/requirement. I'm running on an appliance with multiple NICs connected to different subnets. I can't use HttpURLConnection because I can't control the NIC over which the Box Java SDK API communication will happen.Apache HTTP client supports this. Perhaps, there can be a way that the SDK will allow its default HTTP client functionality to be overridden and be delegated to an external class.
