### ISSUE TITLE
File Name Got Truncated

### ISSUE THREAD

**Issue by ravikantagarwal** [box/box-java-sdk#150]
When I tried to create the file with abc";def then file name got truncated. Also if the file name starts with space than also the leading space got truncated. This issue seems with escaping. I have tried with the box 1.1.0 version.

I have tried to create file with name abc;def and abc"def, these files are successfully created.

I tried to debug the box sdk and found that while writing the filename in the request : Content-disposition header (due to some escaping issue with the file name) the file name got truncated. Please refer(writePartHeader method of BoxMultipartRequest).

I also tried to encode the filename using UTF-8 but that also does not work

Can you please let me how to escape these special character in case of box.

**Comment by gcurtis** [comment]
Thanks for reporting this. You're correct that the filename is being incorrectly truncated for names with `"` and `;`. The `uploadFile()` method needs to be updated to specify the filename in JSON instead of the Content-Disposition header.

Filenames with leading or trailing spaces aren't supported by Box, so those are correctly truncated.

**Comment by ravikantagarwal** [comment]
No in box UI we can create a file with leading space, though on box UI the leading space is not visible but when we try to rename the folder it displays the leading space, even if we fetch the name of file using sdk that filename also contains leading space

**Comment by gcurtis** [comment]
Sorry, I misread the docs. Leading spaces should be permitted but trailing spaces are not.
