### ISSUE TITLE
Using the same refresh token when creating connection instances concurrently

### ISSUE THREAD

**Issue by funtom-io** [box/box-java-sdk#164]
Box gives the user the ability to generate refresh token that will be valid for 60 days using OAuth 2.0. In my java application I want the user to authenticate himself once in 60 days.
Using the refresh token I want to be able create BoxAPIConnection instances from a different threads or processes. The problem is that when one thread/ process connecting the API, the SDK refreshes the token and it makes the previous refresh token invalid.
Now, a different thread/ process won't be able to use the previous refresh token in order to access the BOX API.
How can I use the refresh token in order to generate an new access token, and to reuse the same RT in concurrent threads or processes?

Thank you.
Oz

**Comment by luyseyal** [comment]
Is the new AppAuth/AppUsers code in 1.2.0-SNAPSHOT a possibility?

**Comment by gcurtis** [comment]
If you refresh using the `BoxAPIConnection.refresh()` method or leave auto-refresh on, then the SDK will handle the concurrent refreshes for you. However, this only works across multiple threads in a single process.

If you want to refresh across multiple processes, then you'll need to disable auto-refresh in the SDK and manually find a way to synchronize the refresh process. The SDK doesn't provide cross-process synchronization of the refresh/access tokens because it's very dependent on your specific use-case.

@luyseyal's suggestion is another way of doing it. [AppAuth][1] doesn't use refresh tokens and allows for multiple instances to all have their own access tokens. It does, however, [cost money][2] if you want to use your application with more than 25 users.

[1]: https://box-content.readme.io/docs/app-auth
[2]: https://developers.box.com/box-platform-pricing/

**Comment by jtrunick** [comment]
We used database locking to accomplish this in Postgres, but we are moving to using Redis/Redisson to ensure tokens stay valid, still a bit tricky though either way.

**Comment by jtrunick** [comment]
@gcurtis Could you describe why you must use "the same instance on each thread"?

My understanding is:
* CAN use an "old" AT/RT pair to access the API (as long as not expired)
* CANNOT refresh an old AT/RT pair (only the latest pair)
* CAN refresh an old AT/RT pair as long as the latest has not been "used"

Given this, as long as only one thread/process calls .refresh() and stores it, it seems all should work fine. I would think its okay to use an old pair while using the latest pair on a separate thread, you just couldn't refresh the old pair.

Is that a proper description? I'm not clear what happens if the same user authenticates twice in our system (uses the same account), will both refresh okay in that case or is the refresh based only on the account/clientID pair?

**Comment by luyseyal** [comment]
@jtrunick  You can authenticate multiple times to get a new chain-of-trust, so to speak. We do this with PrintToBox 1.x on multiple servers because sharing tokens between servers sucks. PrintToBox 2.0 switches to AppAuth to avoid tokens altogether, though it kind of sucks, too, because the AppAuth users are not visible to the enterprise so you can't arbitrarily/easily share folders with them. You have to use a special email address. But it's still better than token hell.

**Comment by jtrunick** [comment]
I think AppAuth isn't appropriate for us, we support Box so our customers can see their files in our app.

We've been using Redis to lock by account our "writer/.refresh() thread" which runs every few minutes, which polls for the latest files. Other threads don't lock (and don't call refresh as well), so should be seemingly safe AFAICT. However, we do get occasional inexplicable token expired errors this way. Upgrading to anything above the 0.7 Java API, is a real problem for some reason as the API seems to behave differently and tokens become unexplainably expired shortly after deploying say 1.1.

**Comment by mattwiller** [comment]
@luyseyal @jtrunick @funtom-io For traditional OAuth2 with refresh tokens, you need different threads/processes to coordinate somewhat to avoid issues around refreshing.  You can generally solve this in two ways:

**Scenario 1:** If all your threads are in the sharing a single instance of the Java SDK in memory (e.g. you have one process that instantiates the Java SDK BoxAPIConnection object and then shares it among multiple threads), then the SDK will use a lock to automatically ensure that only one refresh occurs at a time.  This prevents any issues, since each thread will just wait until the refresh is complete and then use the new set of tokens.

**Scenario 2:** If you have different processes or even different physical machines that do not share the same BoxAPIConnection object in memory, then you need to do some work to ensure that these processes coordinate so they don't refresh over one another.

The common failure mode for Scenario 2 goes like this, if you assume you have two processes called A and B:

0. Process A and B start with the same AT/RT pair, denoted AT1/RT1.  AT1 has just expired.
1. Process A notices that its access token is expired and initiates a refresh.  It sends RT1 to the Box API and gets back AT2/RT2.  It immediately makes an API call with AT2, thus invalidating RT1.
2. Process B notices that its access token is expired, and attempts to initiate a refresh.  It sends RT1 to the Box API, but since that has been invalidated the refresh fails and Process B gets a token error.

The way to solve this is to ensure the following:

1. All processes/machines must share a common store, e.g. Redis.
2. A process that initiates a refresh must write the new token pair to the store before making any API calls with the new tokens.
3. If a process gets an expired refresh token error when attempting to refresh, it should read from the store to get the updated token pair.

We have implemented this logic in the Box Node.js SDK by having a TokenStore interface that developers can implement for their own shared store, and guaranteeing the correct refresh behavior described above in our [token manager](https://github.com/box/box-node-sdk/blob/master/lib/sessions/persistent-session.js#L113).

In the current version of the Java SDK, you'll need to ensure these guarantees yourself using a BoxAPIConnectionListener to perform the necessary steps around the refresh.  I think something like the following should do the trick:

```java
// Read the initial connection state — which includes tokens etc — from your store
BoxAPIConnection api = BoxAPIConnection.restore(clientID, clientSecret, connectionState);
api.addListener(new BoxAPIConnectionListener() {
	@Override
	void onRefresh(BoxAPIConnection apiConnection) {
		String connectionState = apiConnection.save();
		// Write the connection state — which includes the tokens — to your store
	}

	void onError(BoxAPIConnection apiConnection, BoxAPIException error) {
		// Read connection state from the store
		apiConnection.restore(newConnectionState);
	}
});
```

Can you try and see if that solves your problem?
