### ISSUE TITLE
upgrading from 0.7.0 to 1.1.0 fails with oauth refresh error

### ISSUE THREAD

**Issue by aruld** [box/box-java-sdk#165]
We are upgrading to 1.1.0 and it seems oauth refresh is failing. We are seeing this error message when trying to refresh an expired oauth token:

{"error":"invalid_grant","error_description":"Refresh token has expired"}

The code that triggered this error:

``` java
BoxAPIConnection api = new BoxAPIConnection(clientID, clientSecret, boxAccessToken, boxRefreshToken);
api.setAutoRefresh(false);
BoxFolder appFolder = new BoxFolder(api, boxFolderId);//FIRST EX: com.box.sdk.BoxAPIException: The API returned an error code: 401

try {

// check if access token in valid
        BoxFolder.Info info = appFolder.getInfo();

      } catch (BoxAPIException ex) {
          // access token expired, refresh access token
          api.refresh();
// check if access token in valid
            BoxFolder.Info info = appFolder.getInfo();//SECOND EX: com.box.sdk.BoxAPIException: The API returned an error code: 400
{"error":"invalid_grant","error_description":"Refresh token has expired"}
      }
```

**Comment by gcurtis** [comment]
When was the refresh token obtained? They expire after 60 days, at which point you must repeat the initial auth flow again. They also expire after being used, which is why the API returns a new refresh token after each refresh. This could be happening if the same refresh token is being used somewhere else.

**Comment by aruld** [comment]
The refresh token was obtained right before I tested. All I did was replaced the 0.7.0 jar with 1.1.0 jar. Revoked the old refresh token that was issued using 0.7.0 jar and then reconnected to Box using 1.1.0 jar, which provided a new refresh token. I did not make any code changes, so I was expecting all this to work seamlessly.

**Comment by gcurtis** [comment]
Hmmm, did you also use the new access token that came with the new refresh token?

**Comment by aruld** [comment]
Yes, I am testing this in my dev, where the redirect is set to localhost. If I try this code, it works in 1.1.0:
```java
BoxAPIConnection api = new BoxAPIConnection(boxAccessToken);
```
Any idea, why this would not work with 1.1.0, when 0.7.0 worked?
```java
BoxAPIConnection api = new BoxAPIConnection(clientID, clientSecret, boxAccessToken, boxRefreshToken);
```

**Comment by jtrunick** [comment]
+1 I have the same issue

**Comment by jtrunick** [comment]
Any progress on this?

**Comment by jtrunick** [comment]
Box 0.7.0 is the last solid version. I've tried dropping in 1.0, 1.1, 2.0, and 2.1. All of these version cause refresh tokens to expire, whereas 0.7 does not.

I'm probably one of the very few manually refreshing tokens and using redis locking to run on multiple servers, I suspect I'm finding enterprise bugs in the API that normal casual use would not find. I suspect it has something to do with the Java API invoking a call with a newly generated token, thereby causing the previous token to expire. This is critical behavior that would be relatively easy to get wrong.

I'd warn anyone with enterprise mission-critical needs to avoid anything above 0.7 until this bug is eliminated.

**Comment by mattwiller** [comment]
Hey @jtrunick and @aruld — the SDK is on v2.9.0 now and I wanted to check back in to verify that you're still having this problem.  In general, since we're now two major versions forward from v0.7.0, a lot of assumptions from that version might no longer hold true.

Could you verify if you're still seeing this issue with the latest version of the SDK, and if so would it be possible to show me exactly what code you're having the issue with?

**Comment by mattwiller** [comment]
I'm closing this issue for now since we need more information and it's unclear if this is still related to the current version of the SDK.  Also, see #164 for more information about this type of situation and a potential related solution.
