### ISSUE TITLE
ProgressListener totalBytes is 0 during uploadFile

### ISSUE THREAD

**Issue by abelsromero** [box/box-java-sdk#214]
I'm running this Groovy code and everything works fine but the `totalbytes` value in the Listener, which is always 0:

```
// get document from classpath
def is = getResource('sample_100.txt')

def listener = new ProgressListener() {
    @Override
    void onProgressChanged(long numBytes, long totalBytes) {
        println "[Uploading] NumKBytes: ${numBytes/1024} KB - TotalBytes: $totalBytes"
    }
}

FileUploadParams params = [
        content: is,
        name: "My_test_file-${System.currentTimeMillis()}.docx",
        created: new Date()-10, 
        listener: listener
]

// Get folder by ID
BoxFolder folder = new BoxFolder(api, folderID)
println folder.info.name
BoxFile.Info file = folder.uploadFile(params)
```

In my shell I get the following output
```
[Uploading] NumKBytes: 33120 KB - TotalBytes: 0
[Uploading] NumKBytes: 33128 KB - TotalBytes: 0
[Uploading] NumKBytes: 33136 KB - TotalBytes: 0
[Uploading] NumKBytes: 33144 KB - TotalBytes: 0
[Uploading] NumKBytes: 33152 KB - TotalBytes: 0
[Uploading] NumKBytes: 33160 KB - TotalBytes: 0
[Uploading] NumKBytes: 33168 KB - TotalBytes: 0
```

**Comment by gcurtis** [comment]
TotalBytes is always 0 because the `uploadFile()` method is unable to determine the total size of an `InputStream` without reading the entire stream. If you set the size with `FileUploadParams.setSize()` then you should start seeing correct output from the `ProgressListener`. This is what the overloaded `uploadFile()` method does and is why it asks for the total size as a parameter.

Hope that helps!

**Comment by abelsromero** [comment]
> TotalBytes is always 0 because the uploadFile() method is unable to determine the total size of an InputStream without reading the entire stream

Make sense. :+1: 
If you ask me, adding a comment on the JavaDoc would help a lot.
