### ISSUE TITLE
Update Readme Documentation to Guide Users between OAuth (for Enterprise Content/Users) and App Auth (for App Users)

### ISSUE THREAD

**Issue by bpliskow** [box/box-java-sdk#233]
The default [README](https://github.com/box/box-java-sdk/blob/master/README.md) leads with an example related to building on the Box Platform leveraging App Auth and JWT. This is misleading to developers building solutions in which they intend to interact with Enterprise content/users. The OAuth process for this use case is documented [here](https://github.com/box/box-java-sdk/blob/master/doc/authentication.md). Would be great to pull this forward and lead with a question to the developer to determine their use case and _then_ walk through examples using the applicable authentication method.

**Comment by gcurtis** [comment]
Thanks for the feedback. I agree, the layout of the README isn't very clear. I like your idea of leading with a question before going into detail for both auth methods. I'd probably even say that we should move the documentation for authentication methods out of the README, since they're pretty lengthy.
