### ISSUE TITLE
Are there any ways to get file type from Box?

### ISSUE THREAD

**Issue by tranquang9a1** [box/box-java-sdk#262]
Hello all,

I'm currently working with Box SDK. 
I want to know after get file, do we have any ways to get File Type such as image, pdf, video... ?

Regards

**Comment by tarrencev** [comment]
We don't currently support that functionality, and I'm not sure we will in the future, since the 'types' of files is somewhat ambiguous depending on the context. However, we have a documented mapping of extensions to file types in the context of our preview functionality here: https://community.box.com/t5/Managing-Your-Content/What-file-types-are-supported-by-Box-s-Content-Preview/ta-p/327

**Comment by tranquang9a1** [comment]
Ok, thank for your answer ;)
