### ISSUE TITLE
bug: BoxAPIException.getMessage does not properly return the exception message

### ISSUE THREAD

**Issue by pgoldweic** [box/box-java-sdk#265]
In the Java sdk, I noticed that if I call BoxAPIException.getMessage(), instead of obtaining the actual exception's error message (which is the value of the 'message' field), I obtain the following:
'The API returned an error code: <error code>', which is certainly useless (as the code is already being returned from the BoxAPIException.getResponseCode() method).  I understand that we can always  parse the json returned in BoxAPIException.getResponse() to be able to classify the error as belonging to a more specific subtype of the error code, but having the getMessage() method actually work, would make it even easier to discriminate.

**Comment by tarrencev** [comment]
Hi @pgoldweic, thanks for reporting this. I'll try get this fixed in the next couple weeks

**Comment by pgoldweic** [comment]
Great! Thanks for the update.

**Comment by mattwiller** [comment]
Hi @pgoldweic — recent versions of the SDK (since v2.5.0) should have the full error object JSON in the message returned by `.getMessage()`.  It sounds like that should solve your problem, but if not please feel free to open a new issue.  So sorry for the delayed response; going forward we'll be much more timely in responding to GitHub issues.
