### ISSUE TITLE
Upload succeeds but file missing the content

### ISSUE THREAD

**Issue by Dezzsoke** [box/box-java-sdk#292]
I have uploaded close to 24k files to a folder. 
Approx 430 files were uploaded as 0 Bytes.

I only upload files from the source which is bigger than 1000 bytes.
Since I'm catching all the errors from box I know I haven't received any error that relates to upload failure.

How could we lose the file content during upload? My understanding is that if I use the API like this:
BoxItem.Info uploadInfo = folder.uploadFile(bis, fileName);
boxFileId = uploadInfo.getID();
Then I only get a fileId if the upload was successful. If it wasn't then I shouldn't see a 0 byte file.

As a workaround I get the size and check that with the original file:
BoxFile file = new BoxFile(api, boxFileId);
BoxFile.Info info = file.getInfo("size");

If it doesn't match I delete the file.

Unfortunately I don't have a way to reproduce this with 100% success. But this affects 1,8% of the files. Frankly we noticed this during the QA test, but our production data could have gone missing as well.

**Comment by dmaynard** [comment]
This seems strange, and I haven't seen this before.  Is there any chance that the 0 byte length is a temporary state due to some asynchronous operation on the back-end?  Can you verify that the files remain in a 0-byte state?   If you would like me to try to dig into our server logs to see if I can find any anomalies you could send me your api-key,  time period and if possible a file-id of one of the 0 byte files to dmaynard at box dot com and I will see what I can find in our logs

**Comment by Dezzsoke** [comment]
It took me a while to point out my own dumbness. I'll write it down so others can learn from my mistake.

We're uploading data from an oracle database. (BLOB / bytea) My mistake was that if an upload failed (lets say because of network, or the fact that our tokens are valid only for 5 minutes) I simply re-tried the upload. But failed to reset / recreate the ByteArrayInputStream . Hence 2nd try it seen an empty stream. 

Ouch.
