### ISSUE TITLE
BoxUser.getCurrentUser(...) should return BoxUser.Info

### ISSUE THREAD

**Issue by dorfire** [box/box-java-sdk#298]
And the worst thing is - both requests have identical responses, with all user info fields.

**Comment by ppaulauskas** [comment]
Hey @dorfire,

What are you executing where you're seeing two requests being made? I checked the method, walked through it and couldn't find where a second request was being made. Checking the internal logs against my API key also shows that only a single request is being received when I run the getCurrentUser call.

```java
0    public static BoxUser getCurrentUser(BoxAPIConnection api) {
1        URL url = GET_ME_URL.build(api.getBaseURL());
2        BoxAPIRequest request = new BoxAPIRequest(api, url, "GET");
3        BoxJSONResponse response = (BoxJSONResponse) request.send();
4        JsonObject jsonObject = JsonObject.readFrom(response.getJSON());
5        return new BoxUser(api, jsonObject.get("id").asString());
6    }
```

Line 1 builds the URL for the endpoint
Line 2 constructs the request
Line 3 sends the request to the URL from line 2
Line 4 parses the JSON response
Line 5 constructs a BoxUser model from the parsed JSON information

The request is only sent during line 3 execution, what behavior are you seeing?

**Comment by dorfire** [comment]
I was unclear. `BoxUser.getCurrentUser(...)` issues a single request, gets all user data fields from the server, and returns a BoxUser object (_which only has the user ID_).

To use the rest of the user information, one must call `user.getInfo()`, **and it issues another request**.

**Comment by ppaulauskas** [comment]
Got it, understood. The ```getCurrentUser()``` method was initially designed to retrieve the user and create a BoxUser model from the information so that you can generate a BoxUser without knowing information about the user outside of the relation that their access token has to their account. You can generate a user utilizing the ```BoxUser(api,id)``` if you do happen to know the user id already, and do a ```.getInfo()``` at that point to generate the BoxUser.Info model.

Thinking through this, I understand the value that you're describing. Adding a new method that would not dispose of that information so that you could still generate BoxUser via the ```getCurrentUser()``` method, but implement a very similar method along the lines of:
```java
public static BoxUser.Info getCurrentUserInfo(BoxAPIConnection api) {
   ...
}
```
This would return the BoxUser.Info model, from which you could construct a BoxUser model using the constructor mentioned above by referring to the id returned from the above call cutting the outbound API calls to one.

I'll look into other subclasses, but I believe Users may be a special case here, because to retrieve information around other resources, you would pretty much always be referring to an id (whether file, folder, collaboration, etc.), while with users, you can get user information directly from the special user endpoint of _.../users/me_ (specifically not utilizing a user id) which does not exist for other resources.

**Comment by dorfire** [comment]
Thanks for the quick response.
Looking forward for a resolution :)

**Comment by gcurtis** [comment]
I think returning a plain `BoxUser` instead of `BoxUser.Info` might've just been an oversight. I can't think of any reason not to return a `BoxUser.Info` object instead. It will require changing the method signature though, so I'm going to triage this issue as a breaking change for v3.0.0.

**Comment by mattwiller** [comment]
This is something we'll need to think more about if we ever decide to do a breaking major-version release.  I think that having two objects (BoxXYZ and BoxXYZ.Info) is confusing in general and we may want to explore if we can have a single class in the future that both holds the field data for the object and allows method calls to perform actions.  I'm going to close this issue since we're not really planning to make the tactical fix suggested here, but this type of issue definitely top of mind for us as we think about how we would want to design a v3.0.0 of the SDK.
