### ISSUE TITLE
Iterators should notify of their pagination progress

### ISSUE THREAD

**Issue by dorfire** [box/box-java-sdk#332]
A rough example of an idea I had:

``` java
BoxFolder folder = new BoxFolder(api, id);

Iterable<BoxItem.Info> folderItems = folder.getChildren();
folderItems.setRequestListener(myObj);

for (BoxItem.Info item : folderItems) {
    ...
    // After every page, e.g. 1000 items, the SDK will call myObj.onRequest(...)
}
```

**Comment by gcurtis** [comment]
This is an interesting idea. It would probably require a cast though, since methods return a plain `Iterable` object.

I guess this could also be accomplished using a `RequestInterceptor`, but it'd probably be messy. Do you have any specific examples of where this functionality would be useful for you?

**Comment by dorfire** [comment]
In my specific project - statistics and progress reports.
