### ISSUE TITLE
Error when used BoxItem.getSharedItem(api, sharedLink) to get BoxFolder of Folder Shared Link

### ISSUE THREAD

**Issue by shenqinb** [box/box-java-sdk#403]
I used BoxItem.getSharedItem(api, sharedLink) to Get Box Item by Shared Link
1. Get Box File by File Shared Link - success
2. Get Box Folder by Folder Shared Link - always get error:
{"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"unavailable","message":"Invalid value 'd_21968929933'."}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"111356121458d12bd746b07"}
is anyone can help?

**Comment by shenqinb** [comment]
I tested again:
1. if I set Box Folder Shared Link to People in this Folder , it works
2. if I set Box Folder Shared Link to People in your Company, it get error
BWT, I use Box JWT OAuth

**Comment by shenqinb** [comment]
I still meet the same problems on File Shared Link, is anyone can help?

**Comment by KarthikShanmugasundaram** [comment]
@shenqinb 
What works:
Enterprise A: User 1 and User 2 belongs to Enterprise A.
   User 1 creates a folder. The folder is not collaborated with user 2. Now, using the access token of User 2, I am calling the method. It works.
    BoxItem.getSharedItem(api, sharelink);

What does not work:
Enterprise B: User 3 belongs to Enterpise B
   User 3 creates the folder. The folder is not collaborated with User 3. Now,  Now, using the access token of User 2, I am calling the method. It does not work.
    BoxItem.getSharedItem(api, sharelink);

This is because the permissions on the shared folder. When create the shared link please check what is the permission the shared link is assigned with.
