### ISSUE TITLE
API should honor "Retry-After" header

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#438]
API should honor "Retry-After" header

Right now it just does a bland backoff with timed wait.

**Comment by mattwiller** [comment]
Hey @nddipiazza — in error scenarios (e.g. a 429 Too Many Requests or 500 Server Error response from the API), it's actually considered best practice to implement exponential backoff with randomized jitter — both [Amazon](https://docs.aws.amazon.com/general/latest/gr/api-retries.html) and [Google](https://cloud.google.com/storage/docs/exponential-backoff) recommend this for their API consumers.  This is due to the fact that in these types of situations, the API may not really be able to tell how long a given client should wait before making another request.  Exponentially backing off ensures that client quickly falls below the rate limits and/or stops hammering API servers that may be failing due to high load.  Randomized jitter helps prevent a [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem) when multiple processes all retry in sync and generate excessive load on the API, by spreading those retries out over a window of time.

The Java SDK doesn't yet implement the randomized jitter, but it's something that's on our roadmap for the next couple months.  Since we're planning to stick with the current strategy of exponential backoff for error scenarios, I'm going to close this issue on the related pull request.  That said, please feel free to re-open for discussion if you'd like to talk further about it!

**Comment by nddipiazza** [comment]
What are you customer doing that are making millions of requests are they doing back off only or are they using the headers and doing back off?

**Comment by mattwiller** [comment]
@nddipiazza For error scenarios (e.g. 429, 500) the recommendation is to just ignore the header and do exponential backoff with random jitter.  For "success" responses that include a Retry-After (e.g. a 202), the header should be respected.

**Comment by nddipiazza** [comment]
Will do thank ye

**Comment by nddipiazza** [comment]
hey @mattwiller those poses an issue for us.

right now box-java-sdk in `master` automatically attempts retries with no respect to expo retry nor retry-after header.

and without this PR large numbers of concurrent requests freezes completely (it will completely freeze due to thundering herd problem).

When are you going to implement the expo retries? I'd really like to get *off* of custom versions of box-java-sdk in production.

If this isn't on schedule for many months... please tell me what retry library you are going to use? or are you going to just write it by hand with a while loop? Being that the use case is pretty simple, adding a library like https://github.com/rhuffman/re-retrying is probably not going to be too necessary. 

Please let me know.

**Comment by mattwiller** [comment]
Hey @nddipiazza, my understanding is that the SDK already implements exponential backoff in [BackoffCounter][backoff-counter] — the `calculateDelay()` method does `2 << exponent`, which is equivalent to `Math.pow(2, exponent + 1)`.  Are you seeing different behavior?

In any case, we're planning to ensure that the Java SDK has correct exponential backoff with randomized jitter in the next three months — probably by the end of March.  We'll likely just implement it ourselves rather than using a library.

[backoff-counter]: https://github.com/box/box-java-sdk/blob/master/src/main/java/com/box/sdk/BackoffCounter.java

**Comment by nddipiazza** [comment]
@mattwiller yes. at one of your biggest clients we did *extremely* large file fetches and until we added the "Retry-After" waits, the fetches would completely freeze and not continue. 

So whatever was there as of about 8 months ago definitely isn't sufficient.

**Comment by mattwiller** [comment]
@nddipiazza To help us make sure we're doing the right thing here, can you give us a bit more context on what you saw with those large file fetches?

1. What SDK method were you calling that froze?  What does "froze" mean in this context?
2. How large is _extremely_ large?  More than 2GB?
3. Do you know what value you were using for `api.getMaxRequestAttempts()`?
4. Do you have any record or memory of what sort of values you saw coming back in the Retry-After header?
5. How did you implement the Retry-After wait?  Just re-calling the SDK method after some period of time, or something more sophisticated?

In any case, I'll definitely make sure to keep you in the loop as we develop this functionality — any help testing in real-world scenarios would be very much appreciated.

**Comment by nddipiazza** [comment]
I was using "crawling" through files using the jwt service account. and i was fetching 1,000,000's of docs (TB's and TB's of content)

When increasing our thread count to any more than a few, the crawl would freeze.

We were simply doing a listing: list all files at users root, download each file recursively until out of files, move to the next one. 

we did this in a "phased" approach where phase 1 we download all file metadata first, and phase 2 we download all the content.

We couldn't even list all the files and their metadata without it freezing completely where the API was simply always getting responses with "retry-after"

i don't remember what max atteps was.

The PR that was closed has the code i was using to get fixed.

**Comment by nddipiazza** [comment]
@mattwiller hi. how is the randomized jitter fix working?

**Comment by mattwiller** [comment]
@nddipiazza We added 50% randomization around the exponentially-increasing backoff time to try and avoid thundering herd problems, and also increased the default number of of retries from 3 to 5.  That __should__ help most clients work through getting hit with rate limits, since in the final retry they would be waiting anywhere from 16-48 seconds before making the API call again.  In all but the most extreme cases, this should suffice to get back under the rate limit.
