### ISSUE TITLE
create folder with managed user

### ISSUE THREAD

**Issue by nicmaster** [box/box-java-sdk#472]
com.box.sdk.BoxAPIException: The API returned an error code: 404
{"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"parent","message":"Invalid value ''. 'parent' with value '' not found"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"36082549559cb98c7e0cad"}] with root cause

**Comment by mattwiller** [comment]
Hey @nicmaster — could you show us the code you're using to make this request?  It looks like you might not be correctly specifying the parent folder for the new folder you're trying to create.  All new folders need to have a parent folder; if you're trying to create a folder in the user's All Files (i.e. the root of their filesystem, you can do something like this:

```java
BoxFolder root = BoxFolder.getRootFolder(api);
root.createFolder("New Folder Name");
```

Otherwise, you should specify the parent folder ID like this:

```java
String parentFolderID = "123456789";
Box Folder parent = new BoxFolder(api, parentFolderID);
parent.createFolder("New Folder Name");
```
