### ISSUE TITLE
Started getting api status 400 error suddenly - `Please check the 'jti' claim.`

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#475]
We are on 

`com.box:box-java-sdk:2.4.0`

We have CI servers that run some very small tests that use integration tests that utilize read-only Box.com. This CI box test, after working for a long time with no problems, suddenly started giving us this error:

`{error:invalid_grant,error_description: Please check the 'jti' claim.}`

What might this be?

**Comment by mattwiller** [comment]
Hi @nddipiazza — could you provide some additional information to help us debug?

1. How often is this error occurring?  Is it every time, in bursts, or something else?
2. Can you tell us a bit about what this CI test is doing?  What sort of operations does it perform against the Box API, and in what order?
3. When exactly did this error start happening?

In general, errors with the `jti` claim are usually caused by either faulty ID generation logic (the Java SDK uses 64 random bytes, which should be fine) or by a problem between the SDK and the API.  One thing that I've seen cause problems is request retries — retrying the authentication request can sometimes require a new JWT ID to be generated and put into the `jti` field.  If possible, can you help us verify if you're seeing authentication requests being retried on your end?

**Comment by svanloon** [comment]
I'm on 2.8.2.   I have 2 boxes that are running doing conversions.   They have 5 threads each box and currently they are getting their own connection with their own access token cache.   We are using JWT.    When I add a 3rd box (same configuration), the first 2 boxes start failing.   The 403 jti errors start happening and then I start seeing the 429 rate limit errors.   It's like the 3rd box has tried to get its own keys and that's making the other 2 boxes keys invalid.   When I stopped the 3rd box, the errors disappeared from the 2 boxes.  I will be doing more tests tomorrow and see if I can get more details.  I'm going to see if I'm getting new access token keys for the thumbnail retrieval.   The actual thumbnail retrieval is done outside of the sdk because it's a representation call (inside the sdk) and then download thumbnail (direct call outside of sdk).

**Comment by mattwiller** [comment]
@svanloon It sounds like the introduction of the extra box is causing you to hit rate limits, which is then causing the SDK to retry auth requests, which is running into a condition where the `jti` claim has already been consumed before the previous request was rate limited.  I think this is something we can fix within the SDK by regenerating the `jti` claim before retrying — I'll get started on that change this week.
