### ISSUE TITLE
Getting not_enough_space error with unlimited  storage option

### ISSUE THREAD

**Issue by abhi8344** [box/box-java-sdk#552]
I am trying to move folders across accounts using the method moveFolderToUser and am getting the following response back

Response Message : {"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"not_enough_space","request_id":"#########"}

We have unlimited storage option for users

**Comment by mattwiller** [comment]
Hi @abhi8344 — you blanked out the `request_id`, but it's actually not sensitive information and would be useful for me to start debugging.  Would you mind adding it here?

**Comment by abhi8344** [comment]
{"type":"error","status":400,"code":"bad_request","help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"not_enough_space","request_id":"5me3oofo2egvqv1k"}

**Comment by mattwiller** [comment]
I can't find anything to suggest this is an SDK issue — I would suggest a few things:

1) Double-check that the target user actually has unlimited space, just in case.
2) Verify that the enterprise that the target user is in has sufficient storage space — the user being unlimited doesn't matter if the enterprise has reached its storage quota.
3) Since this doesn't appear to be an SDK issue, I would recommend [contacting Box Support](https://community.box.com/t5/Contact-Support/ct-p/BoxSupport#) — they have the tools to help debug this sort of problem.
