### ISSUE TITLE
Error parsing PKCS private key for Box Developer Edition in JAVA 1.8.0_161

### ISSUE THREAD

**Issue by misterfifi1** [box/box-java-sdk#567]
Hi, 

I am using the latest version of JAVA 1.8, which contains by default the unlimited Policy setting required for PKCS Private key. Unfortunately, when I create a JAR then launch it with the save java version I get this error: "Error parsing PKCS private key for Box Developer Edition"

Java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

FYI the Cipher.getMaxAllowedKeyLength("AES") returns: 2147483647, so should be enough to work.

I hope that you can help me. 

Regards,

**Comment by mattwiller** [comment]
Hi @misterfifi1 — could you give us some more information to help diagnose this issue?  Specifically, it would be really helpful if you could provide the full error message and stack trace for the error you're seeing — the class of error that produces the message you see is pretty general and could have a number of causes.  As you've mentioned, it doesn't seem like it's due to the Unlimited Strength Policy — we'll need more information to figure out what might be causing it.

**Comment by misterfifi1** [comment]
Hi, 

Please find below the info I got from the stacktrace: 
- **Cause** : org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: JCE cannot authenticate the provider BC
- **Class**: class com.box.sdk.BoxAPIException
- **Message**: Error parsing PKCS private key for Box Developer Edition.

Thanks for your help

**Comment by mattwiller** [comment]
@misterfifi1 I'm not familiar with that specific error, but a quick Google search shows that it may be related to exactly how your application pulls in BouncyCastle: https://stackoverflow.com/questions/13721579/jce-cannot-authenticate-the-provider-bc-in-java-swing-application

How is your application getting BouncyCastle — are you using Gradle or something similar, or manually pulling in a jar file?
