### ISSUE TITLE
Enhance Folder - File creation and name check with Utility Method such as isFolderExists or isFileExists

### ISSUE THREAD

**Issue by ptrivedi9400** [box/box-java-sdk#573]
- [X] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
Using Java SDK If I create a folder then there is no way to verify/check if the folder exists. though API itself does support to have an ETAG of IFEXISTS I am surprised by not seeing a simple method like `isFolderExists` or `isFileExists` method on any of the existing Box class. the only way to verify is to getInfo on BoxFolder and if the object is null then create new folder otherwise. If we have such utility method in BoxFolder and BoxFile.info then it might be useful for developers to use it to avoid exception like folder/file already exists.

### Versions Used
Java SDK: 2.15.0  
Java: 1.8.0_152

### Steps to Reproduce
This is not a bug. it's more inline with enhancement if stakeholders agree than.
[BoxFolder.info](https://github.com/box/box-java-sdk/blob/master/doc/folders.md#get-a-folders-information)

There are workarounds like catching the exception or handling something with if the condition on Iteration or in case of Optional.Of the isPresent manner in Java 8.

```
BoxFolder folder = new BoxFolder(api, "id");
for (BoxItem.Info itemInfo : folder) {
    if (itemInfo instanceof BoxFile.Info) {
        BoxFile.Info fileInfo = (BoxFile.Info) itemInfo;
        // Do something with the file.
    } else if (itemInfo instanceof BoxFolder.Info) {
        BoxFolder.Info folderInfo = (BoxFolder.Info) itemInfo;
        // Do something with the folder.
    }
}
```
or

```
Collection<BoxItem> folderItems = new ArrayList<BoxItem>();
BoxFolder folder = new BoxFolder(api, "id");
for (BoxItem.Info itemInfo : folder) {
    folderItems.add(itemInfo.getResource());
}
```
Personally don't think its efficient way of handling one check. Box SDK should have such utility method 
for a check.

### Error Message, Including Stack Trace
N/A

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@ptrivedi9400 Can you give some more detail on what your use case is here?  It looks like you have a folder ID and need to see if it exists — if not, then create a new folder in its place?  What sort of cases are you dealing with where you have an ID but don't know if the item actually exists or not?

**Comment by ptrivedi9400** [comment]
@mattwiller use case creates a folder for your customer with customer_id and store necessary submitted documents for their application. now the same customer can come tomorrow with additional documents of updated documents then we need to update those document otherwise create documents. Each time we do process we need to make sure it's not the first time customer is coming. if the customer is the first time then create new folder otherwise use existing folder only as we don't want multiple document container folders for same customer id. BTW there is no ID there is actually a folder name which needed to be verified as the error does not throw on basis of ID but on the basis of the same name of folder and files. Hope this helps.

**Comment by ptrivedi9400** [comment]
one another option is to have a versioning of the documents/folder means if the folder exists it override it but at the metadata level, it will mark it as version 2. same for files too.

**Comment by mattwiller** [comment]
I see — thanks for the explanation, it definitely helps me understand what you're trying to do.  In general, I wouldn't really advise using the folder name to correspond to your own customer ID this way.  There is a uniqueness constraint on the folder name today, but there's no hard guarantee that Box will always enforce that uniqueness.  It could be considered essentially an implementation detail.  Here are two more robust ways to handle this issue:

- You could use some sort of database or store in your application to map your customer ID to their Box folder ID so you don't have to rely on the folder name uniqueness constraint.  This would let you quickly check if a folder has already been created for a given customer or not, and get the correct ID directly if it had been created.
- If you're using JWT authentication, you could also [create an App User](https://github.com/box/box-java-sdk/blob/master/doc/users.md#create-an-app-user) for each customer you have — this would automatically give you a unique folder structure for each customer.  You could set your customer ID as the Box App User's external ID, which would allow you to easily [look up if the app user already exists](https://github.com/box/box-java-sdk/blob/master/doc/users.md#get-app-users-by-external-app-user-id) in your application.

If you do want to use the folder name, I don't think that the SDK should be in the business of handling this kind of application-specific logic.  As you pointed out in your original post, there are already well-supported ways of iterating through all the items in a folder to find one with a given name.  I don't see a real need to put that logic into the SDK when it's straightforward to implement in your own application — the code you pasted above should work just fine.

**Comment by ptrivedi9400** [comment]
looks like the box is not a version based content mgmt system. if that is the case then we can close this issue. Thanks for your suggestions. appreciated.

**Comment by mattwiller** [comment]
@ptrivedi9400 Box supports versions for files, but not folders.  In the next month or so we'll be implementing a feature to get items by path rather than ID, which should also help solve your use case — you could look up the folder directly when the creation fails rather than needing to iterate over all items in the root folder.  I'm going to close this ticket since we will not be implementing the method you're requesting, but I would encourage you to check back in a month or so to get the new functionality which should help you out.

**Comment by worpet** [comment]
@mattwiller is there any update on the feature to get items by path?

> In the next month or so we'll be implementing a feature to get items by path rather than ID, which should also help solve your use case — you could look up the folder directly when the creation fails rather than needing to iterate over all items in the root folder.

I wasn't able to find a method to do something like this. I checked the developer forums, but did not find further info other than it's been a common request.

- https://support.box.com/hc/en-us/community/posts/360049201633-How-to-get-file-ID-from-the-API-
- https://support.box.com/hc/en-us/community/posts/360049199313-Find-Folder-ID-given-a-path-Python-SDK-
- https://support.box.com/hc/en-us/community/posts/360049150014-File-Pathing-Please-help
- https://support.box.com/hc/en-us/community/posts/360049198713-How-to-get-id-if-i-know-the-path-using-rest-api-
- https://support.box.com/hc/en-us/community/posts/360049188293-Uploading-Files-and-Folders-to-Box
- https://support.box.com/hc/en-us/community/posts/360049142434-View-File-using-File-Path
- https://support.box.com/hc/en-us/community/posts/360049133494-Quering-path-of-Box-Sync-folder
- https://support.box.com/hc/en-us/community/posts/360049185073-Uploading-Files-and-Folders-to-Box-using-Box-Java-SDK-Api

The search ability is close, but it doesn't return new files or folders for about 10 minutes after they are created, so it's not reliable.

[`BoxFolder#canUpload(String fileName, long fileSize)` ](http://opensource.box.com/box-java-sdk/javadoc/com/box/sdk/BoxFolder.html#canUpload-java.lang.String-long-) is also close. Since a call to this will return, among other info, the ID of the file with that name if it already exists, it seems Box must internally have a way to look up things by name and that functionality could be exposed to the API as a lookup method.
