### ISSUE TITLE
Invalid Parameter (Adding 'd_' automatic )

### ISSUE THREAD

**Issue by ankur-appronic** [box/box-java-sdk#680]
Hello Team,

I am adding following code to create a new folder on the box.com. 
BoxPlatformApiConnection api = makeConnection();
BoxFolder parentFolder = new BoxFolder(api,'64587671011' );
parentFolder.createFolder(folderName);

but getting following response.

response body: {"type":"error","status":404,"code":"not_found","context_info":{"errors":[{"reason":"invalid_parameter","name":"parent","message":"Invalid value 'd_64587671011'. 'parent' with value 'd_64587671011' not found"}]},"help_url":"http:\/\/developers.box.com\/docs\/#errors","message":"Not Found","request_id":"e0t3hofzhm5be4bj"}

Not able to understand from where '_d' is adding in Parent folder id. Can you please help me out in this case.

More Info: 

I have tried the same thing from postman and found that if we do the call out with the token which we are adding while do from BoxApiRequest class. I am getting the same issue.

![image](https://user-images.githubusercontent.com/44723236/51659380-5159a980-1fd0-11e9-917e-5e979b761c73.png)

Note: Please let me know if you need more info regarding error.

Thanks in advance.

**Comment by pmatte1** [comment]
The issue is likely due to not having access to the folder with the ID 64587671011, or that the folder with that ID does not exist in the enterprise your makeConnection() method is configured to establish a connection to.  While the d_ convention in the error message is misleading, what can be relied upon is the code value of not_found, or the message Not Found, which is alerting you that the item with the ID 64587671011 cannot be found. 

This is not an issue with the SDK, as you noted, the API is actually producing the error you are seeing, and the SDK simply passes that back as an exception, which is proper.

**Comment by ankur-appronic** [comment]
Ok, could you please specify the difference between enterprise and user
related API connection
