### ISSUE TITLE
Folder Udpate: getIsCollaborationRestrictedToEnterprise does not return the correct value

### ISSUE THREAD

**Issue by jacquesvandermerwe** [box/box-java-sdk#704]
- [ x ] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
When a folder is set to restrict collaborations to the enterprise i.e. isRestrictedToEnterprise==true. 

When getting the BoxFolder Info then isRestrictedToEnterprise is always false.

### Versions Used
Java SDK: 		<dependency>
			<groupId>com.box</groupId>
			<artifactId>box-java-sdk</artifactId>
			<version>2.32.0</version>
		</dependency>

Java: 1.8_191

### Steps to Reproduce
			BoxFolder boxFolder = new BoxFolder(boxAPI, FolderId);
			BoxFolder.Info info = boxFolder.getInfo();
			info.getIsCollaborationRestrictedToEnterprise(); -- This will always be false even if its true on the folder.

### Error Message, Including Stack Trace
NA

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

**Comment by mattwiller** [comment]
@jacquesvandermerwe This is a known issue in the SDK; since the field is defined as a primitive `boolean` it always has a value which default to `false`.  Since the `is_collaboration_restricted_to_enterprise` field is not sent back from the API unless requested, you get that default value.  If you want the value to be correct, you'll need to ensure that you're requesting the field from the API:
```java
BoxFolder.Info info = boxFolder.getInfo("is_collaboration_restricted_to_enterprise");
info.getIsCollaborationRestrictedToEnterprise(); // Will be correctly populated
```

**Comment by jacquesvandermerwe** [comment]
Perfect. Thanks @mattwiller
