### ISSUE TITLE
Q: how to check version of SDK? 

### ISSUE THREAD

**Issue by TiloGit** [box/box-java-sdk#728]
how can I check which version the box-java-sdk.jar is? 

I got an embedded Box SDK from IBM software with hash: 
`A22C34A8DE04277B2680177BAE8DC622D06FE619F35EFF480C27C483490D1C2D`

and **BoxAPIConnection.java** contains this
`this.userAgent = "Box Java SDK v1.0.0";`

**Comment by carycheng** [comment]
Hey @TiloGit,

The user agent string that you have copied over is the current Box Java SDK version that is being used which is representative of the version of the jar file. The version of the jar file is also appended at the end so the format would be something like this: `box-java-sdk-<version_number>.jar`.

However, you mentioned that your entry point into the Box Java SDK might stem from IBM? Can you please elaborate a bit more on how you are currently using the Java SDK and your set up? I think that might help us provide you with an even more precise answer.

Thank you

**Comment by TiloGit** [comment]
Packaged in ICN (IBM Content Navigator), to Share via Box and Copy to Box. Also ICN can be front end to Box. 
Connection is `"Standard Oauth (User Authentication)" `and `Oauth 2.0 with JWT (Server Authentication)` depends on the action used

Box SDK locations (before packed as EAR file for deployment on WebSphere): 
`\IBM\ECMClient\configure\explodedformat\navigator\WEB-INF\lib\box-java-sdk.jar`
and
`\IBM\ECMClient\configure\explodedformat\taskManager\taskManagerWeb\WEB-INF\lib\box-java-sdk-1.0.0.jar`

package: **com.ibm.ecm.util.box**

Should this Box SDK version still be good or do we need newer one due to TLS deprecation?  https://developer.box.com/docs/tls-1#section-java

I'm chasing down a `java.net.SocketException: Connection reset` issue. Our Demo system last worked around Feb 2019.

**Comment by carycheng** [comment]
Hey @TiloGit,

Due to the TLS 1.0 deprecation, you will need to upgrade the Box Java SDK version to minimum v2.14.1 in order to connect to Box.

Box Java SDK v2.14.1 is available [here](https://mvnrepository.com/artifact/com.box/box-java-sdk/2.14.1) but if you are making the leap to a new major version I would strongly recommend upgrading to the latest version v2.36.0 found [here](https://mvnrepository.com/artifact/com.box/box-java-sdk/2.36.0).

**Comment by TiloGit** [comment]
Thanks for all your help. I change the WAS setting to TLS 1.2 and could connect with old embedded SDK

Back to root of my Q, the only way to tell the version is bv file name then?

**Comment by carycheng** [comment]
@TiloGit, that's great to hear.

As for the SDK versioning - do you know whether the instance of the Java SDK of you are using is a custom instance packaged by IBM? 

The reason why we need clarification on this is because our SDK is installed through Maven Central seen [here](https://search.maven.org/search?q=g:com.box%20AND%20a:box-java-sdk&core=gav) and the versioning is displayed on both the Maven Central repository as well as the package name in your imports. If the versioning is missing from both then we might believe that the Java SDK instance currently in use might be a repackaged custom instance.

**Comment by PJSimon** [comment]
Hi @TiloGit, I'm closing this old issue, but if you're still having difficulties, please just re-open the issue and let us know!  Thanks!
