### ISSUE TITLE
The API returned an error code [404 | TOKEN1.TOKEN2] not_found - Could not find the specified resource

### ISSUE THREAD

**Issue by dzlab** [box/box-java-sdk#737]
- [x] I have checked that the [SDK documentation][sdk-docs] and [API documentation][api-docs] doesn't solve my issue

### Description of the Issue
I've a file shared publicly (anyone with link can read/download the file) and I'm trying to read this file using Box SDK. I registered the app, authorized it in my account. I successfully created a connection (I can create app/enterprise users, etc.).

Now when I try to read the file with this connection I get `404 not_found - Could not find the specified resource`, but if I generate a developer token I can successfully read this same file.

### Versions Used
Java SDK: 2.38.0
Java: 1.8
Scala: 2.11.12

### Steps to Reproduce
```scala
val api = BoxDeveloperEditionAPIConnection.getAppEnterpriseConnection(ENTERPRISE_ID, CLIENT_ID, CLIENT_SECRET, encryptionPref, accessTokenCache)
val file: BoxFile = new BoxFile(api, FILE_ID)
val output = new ByteOutputStream()
file.download(output)

println(new String(output.getBytes))
```

Also try using a user connection (instead of enterprise connection) but had same error
```scala
val params = new CreateUserParams
params.setSpaceAmount(1048576) // 1 MB
val user = BoxUser.createAppUser(api, APP_USER_NAME, params)

var userApi = client.getUserConnection(user.getID)
println(s"enterprise token ${api.getAccessToken}, user token is ${userApi.getAccessToken}")
val file: BoxFile = new BoxFile(userApi, FILE_ID)
val output = new ByteOutputStream()
file.download(output)
```

### Error Message, Including Stack Trace
The `download` call seems to trigger the following exceptio:
```
Exception in thread "main" com.box.sdk.BoxAPIResponseException: The API returned an error code [404 | TOKEN1.TOKEN2] not_found - Could not find the specified resource
	at com.box.sdk.BoxAPIResponse.<init>(BoxAPIResponse.java:92)
	at com.box.sdk.BoxJSONResponse.<init>(BoxJSONResponse.java:32)
	at com.box.sdk.BoxAPIRequest.trySend(BoxAPIRequest.java:582)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:354)
	at com.box.sdk.BoxAPIRequest.send(BoxAPIRequest.java:329)
	at com.box.sdk.BoxFile.download(BoxFile.java:297)
	at com.box.sdk.BoxFile.download(BoxFile.java:285)
```

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs

What is the proper way to read such a file?

**Comment by carycheng** [comment]
Hey @dzlab,

The problem you are experiencing may be due to scope of the user model you are using. To clarify, Box has a couple different of user models that we use for different use cases:

**Service Account**
- A Service Account represents the application you created in a Box Enterprise. It can only be accessed programmatically similar to an App User, and a Service Account can also be used to create App User accounts. You can read more about Service Accounts [here](https://developer.box.com/docs/service-account).

**App User**
- An App User is very similar to a Service Account in that they are accessed programmatically, but you can create multiple App User accounts. You can read more about App Users [here](https://developer.box.com/docs/user-types#section-app-user).

**Managed Users**
- A managed user represents a member of an enterprise and has an associated login email/password. This is also your personal account. You can read more about managed accounts [here](https://developer.box.com/docs/user-types#section-managed-user).

To bring it all back, we have a few different user models here. The Service Account that you are authenticating as is separate from your personal user account. Each user account has its own separate files and folders. You can access content in another managed account in a few ways:

- Taking actions on behalf of user by [as-usering][as-user].
- Collaborating the account onto the content you want them to have access to.
- [Authenticating as a user with access to the content][authentication] that already has access to that file/folder.

[as-user]: https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#as-user
[authentication]: https://github.com/box/box-java-sdk/blob/master/doc/authentication.md#server-authentication-with-jwt

**Comment by dzlab** [comment]
it seems that I need to make a request as the user who owns this file, but how can I get the user id given a file id?

**Comment by carycheng** [comment]
Hey @dzlab,

You are correct, you will need to make your download request via a user that has  the correct permissions to that file. Depending on the way you are attempting to access this file (as-usering, authenticating as owner, etc...)

1. One way is to check the collaborators of the folder the file belongs to and grab one of the user id's(with at the very least [viewer-downloader](https://community.box.com/t5/Collaborate-By-Inviting-Others/Understanding-Collaborator-Permission-Levels/ta-p/144) access level)from there to as-user into and then perform the download.
2. Another is to grab the file info and inspect the `owned_by` field for the file and grab the user id from there.
3. Third option is if you always know the owner of that folder, you can directly just use the user id of that owner and perform a download on behalf of that user.

**Comment by dzlab** [comment]
I managed to read the file using step 2, and with the help of this box community post. Thanks a lot for the insights.
