### ISSUE TITLE
Update Collaboration

### ISSUE THREAD

**Issue by yogaredhat** [box/box-java-sdk#770]
Hi Team, 

I am following API document to update collaboration on folder .
https://developer.box.com/en/reference/put-collaborations-id/

Under request body  I do see option as expires_at but its not workign as it seems . I tried  API using curl and its not working. I tried SDK and I do not see any option to set expires_at date.

expires_at :string / date-timein bodyoptional
example2019-08-29T23:59:00-07:00
Set the expiration date for the collaboration. At this date, the collaboration will be automatically removed from the item.

Does this options still availble ?. If not is there any way we can expires collaboration for user other than explicity removing it.

**Comment by carycheng** [comment]
Hey @yogaredhat,

In order to set expiration for a collaboration, the `expires_at` field needs to be set at the time of collaboration creation. Unfortunately, you cannot retroactively add it. In order to work around this you can delete the collaboration and re-add it with the `expires_at` field included.

Thank you

**Comment by yogaredhat** [comment]
@carycheng  Thanks for this updates. Hoewever I do see any options to set  expires_at while adding collaboration. Here is how we are adding collaboration on folder. I might be missing something here  But I do not see any options where we can set expires_at. 

BoxFolder folder = new BoxFile(api, "id");
folder.collaborate("gcurtis@box.com", BoxCollaboration.Role.EDITOR);

**Comment by sujaygarlanka** [comment]
@yogaredhat We currently don't have the option to set it when you create a collaboration in the Java SDK. We are looking into adding it in our next sprint.

**Comment by sujaygarlanka** [comment]
@yogaredhat We have a feature in progress to set the expiration date when you create or update a collaboration in the Java SDK. The reason your curl call probably wasn't working earlier is because you must update your enterprise settings under `Content and Sharing` to allow owners to set the expiration date. I have attached a screen shot of where they can be found.
<img width="798" alt="Screen Shot 2020-04-07 at 4 19 10 PM" src="https://user-images.githubusercontent.com/21188938/78715544-8effd500-78eb-11ea-876f-2ef6c5289026.png">

Lastly, there is one quirk regarding this endpoint. When updating a collaboration, you must pass in both the role and the expiration date if you want to update the just expiration date.
