### ISSUE TITLE
Provide options to get events in an enterprise

### ISSUE THREAD

**Issue by tcharles79** [box/box-java-sdk#81]
Hello,

Please provide options to get "events in an enterprise".
API: https://developers.box.com/docs/#events-get-events-in-an-enterprise

We're using below code to get admin events using current SDK. Looking for equivalent in new SDK.

      BoxEventRequestObject boxEventRequestObjs =     BoxEventRequestObject.getEventsRequestObject(stream_position); // pass stream position here       
      boxEventRequestObjs.addQueryParam("stream_type", "admin_logs");
      boxEventRequestObjs.addQueryParam("event_type",	"COLLABORATION_INVITE");
      BoxEventsManager boxEventsManager = client.getEventsManager();

      BoxEventCollection boxEventCollect = boxEventsManager.getEvents(boxEventRequestObjs);
     List<BoxEvent>		eventsList = BoxEventsManager.getEvents(boxEventCollect);
     Long st = boxEventCollect.getNextStreamPosition();

Thanks..

**Comment by gcurtis** [comment]
Work will begin on this right after #79 is completed.

**Comment by gcurtis** [comment]
Just a quick update on this - we've hit some roadblocks due to the API returning some unexpected JSON. We want to see if it's reasonable to fix the API or if we should work around it in the SDK.

**Comment by gcurtis** [comment]
Hi @tcharles79,

You should now be able to retrieve a log of enterprise events using the `EventLog` class. Due to some bugs in the enterprise events endpoint, you'll probably have to use the `BoxEvent.getSourceJSON()` method instead of `BoxEvent.getSourceInfo()`. The reason for this is that not all enterprise event sources correctly map to a `BoxResource.Info` object, so instead you have to access the JSON fields manually.

 Let me know if you have any other questions or issues!

**Comment by tcharles79** [comment]
Seems we need to pass before and after dates to get the events. Is it possible to get the events based on stream position alone?

**Comment by gcurtis** [comment]
Unfortunately it isn't. The API requires that we pass `created_after` and `created_before` dates - https://developers.box.com/docs/#events-get-events-in-an-enterprise

**Comment by tcharles79** [comment]
When using getSourceJSON(), i'm getting only the source block, but i need other blocks as well (created_by, additional_details).. 
Let me know how to get those. Thanks.
