### ISSUE TITLE
Deserialize webhook payload into BoxWebHook object (or another POJO)

### ISSUE THREAD

**Issue by vladokrsymphony** [box/box-java-sdk#814]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.

### Description of the Issue
When receiving a webhook payload we would like to be able to deserialize the JSON payload to a POJO which is defined inside the SDK, and to avoid creating POJOs on our side. I believe this is a good  functionality which should be provided by the SDK. If it is already the case, please provide an example, because so far I was not able to find one.

The BoxWebHook Info has a constructor which receives a JSON object.
Therefore I tried is something like following code:
`
@RestController
@RequestMapping("/event")
public class EventController implements EventOperations {

    private static BoxWebHook webhook = new BoxWebHook(null, null);

    @Override
    public String create(@Valid String event) {    
        JsonObject jsonEvent = JsonObject.readFrom(event);
        BoxWebHook.Info info = webhook.new Info(jsonEvent);
        ...
    }
}
`

I send to the controller a sample payload defined at:
https://developer.box.com/guides/webhooks/handle/payload/#Payload-body
The payload was not deserialized correctly.

### Expected Behavior
We would like to have a POJO in which we can simply deserialize the webhook payload, and to avoid maintaining those POJO on our side. 

### Versions Used
Java SDK: 2.32.0
Java: openjdk version "1.8.0_222-4-redhat"

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by sujaygarlanka** [comment]
@vladokrsymphony The webhook functionality in our SDK is meant to match with the API endpoints [here](https://developer.box.com/reference/get-webhooks). So our SDK allows you to interact with webhooks by getting, creating, listing, etc. The objects returned from these endpoints and deserialized in our SDK are Webhook objects (i. e. The configuration fo the webhook), not Payload objects. This is why passing in the payload to the Webhook is not working. Payload objects can vary unlike Webhook objects to be files, folders, weblinks, etc., which is why we don't have a Model object for them. We do provide payload validation found [here](https://github.com/box/box-java-sdk/blob/master/doc/webhooks.md#verify-a-webhook-message). A guide on what this is can be found [here](https://developer.box.com/guides/webhooks/handle/setup-signatures/). I hope this answers your question. If you have any follow-up questions, feel free to re-open this.

**Comment by vladokrsymphony** [comment]
@sujaygarlanka  Thank you very much for your explanation. Unfortunately, it didn't provide an answer to my question.
I do understand that BOX SDK allows to create/manage webhooks and helps to validate the Webhook's payload using the primary and the secondary key.  However my request is to know if the SDK has an object POJO to which we can desalinize the [payload ](https://developer.box.com/guides/webhooks/handle/payload/) upon receiving an event.
