### ISSUE TITLE
why did you deprecate box api batch requests?

### ISSUE THREAD

**Issue by nddipiazza** [box/box-java-sdk#817]
simple question

why did you deprecate box api batch requests?

it made our api application much faster.

**Comment by PJSimon** [comment]
Hi @nddipiazza ,

Thanks for the question and yes, we definitely can understand that batch requests can be helpful.  I'll look into this and get back to you, but I don't think there are any plans to add it back.

Thanks,

Patrick

**Comment by jcleblanc** [comment]
Hi @nddipiazza,

I can add some context on the historical reasoning, and our goals for the future. 

Originally the Batch API was released for a very limited number of customers with a very specific use case, to bundle a series of API requests together to reduce the roundtrip time of those requests due to only one connection being created. The API doesn't reduce the number of calls being made on the Box side, leading to inefficiencies and confusion as to its overall purpose, which is why it was never documented on the [developer site](https://developer.box.com/) and not officially released. 

Nearly a year back we added a warning into the Batch method (I believe that's what you're referring to) stating that the feature is being deprecated. The purpose in doing this was to relay the unsupported state of the API to our customers without actually breaking the feature. In short we want folks like yourself to know that this is on our list for overhaul, and to know that changes may be coming. One of our most impactful processes with the APIs is when we EOL a feature, and we want to ensure that we reduce impact on our customers as much as we can.

Just to note, there is currently no planned date to EOL that API and remove the functionality, nor is there a date on the roadmap to target the overhaul of the feature, so this isn't happening in the near term. Our future goals are to rearchitect the Batch API to make it more effective for all of our customers, rather than just fitting a very narrow use case for just a few. In a reimagined Batch API the same round trip time benefit would still be present.

I understand the frustration here, and please accept my apology for any issues this may cause. Just know that we're working towards ensuring the stability and usability of the Platform holistically with these efforts. 

Happy to answer any other questions if there is any other info you may want.

- Jon
