### ISSUE TITLE
bcprov-jdk15on dependency vulnerable

### ISSUE THREAD

**Issue by daanhorn** [box/box-java-sdk#859]
### Description of the Issue
The version of the bcprov-jdk15on dependency has a vulnerability. Please update to latest version. As a workaround I've currently overruled the version of bcprov-jdk15on and bcpkix-jdk15on being used in my project.
More info: https://snyk.io/vuln/maven:org.bouncycastle:bcprov-jdk15on

**Comment by sujaygarlanka** [comment]
@daanhorn Thank you for reporting this. We will take a look at it and respond ASAP.

**Comment by antusus** [comment]
Hello @daanhorn ,

we are forced to use `org.bouncycastle:bcprov-jdk15on:1.57` and `org.bouncycastle:bcpkix-jdk15on:1.57` because they are compatible with `org.bouncycastle:bc-fips:1.0.2.1`. The latter has the FIPS certification https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/3514
which is required by some of our customers.
I'm afraid that for now I can only suggest to overrule and force other version of `bcprov-jdk15on` in your project.
