### ISSUE TITLE
Chunked uploads to support user's determined chunks.

### ISSUE THREAD

**Issue by jgoldverg** [box/box-java-sdk#909]
Hello everyone I have a feature request for the Java SDK to support chunked uploads where the user can determine the chunk sizes themselves.

The situation currently is I currently have a service that runs batch jobs to a few cloud storage solutions Box included. The data varies in size greatly sometimes files are 20MB all the way until 900GB being the largest file I have had so far. 
Currently uploading files less than 50MB has been trivial and super easy based on the documentation. 

The problem is with uploading larger files greater than 50MB. When I try and do chunked uploads the BoxFileUploadSession class supplies the required chunk size, which is inadequate for my use case. 

For example I am trying to use a 100MB chunk size as my link is massive(40 GbE) on a 1GB file. But the Box SDK is giving me an error saying that it wants me to use a chunk size of 33554432 bytes=33.55MB chunk size.

I would it like if the chunk size is an optional parameter for the user to supply when creating a chunked upload session.
I believe there should be a minimum chunk size imposed on all transfers, as for example trying to send 900GB with a chunk size of 64KB is ridiculous. Examples of this feature are S3 & Google Drive Java SDK which both have minimum chunk sizes(S3: 5MB & Google Drive: 256KB lower bound chunk sizes) and allow the user to pass in their own chunk size to use. 

To support the current Box SDK I would need to resize all of my chunks to match the size that the Box SDK wants me to use. So during my Batch Job after reading in a symmetric partition of data I would need too resize the partitions to match what the Box SDK would want me to use. This extremely expensive for my service and would certainly be the bottle neck of writing data to Box.

A question I have is how does the current Box SDK determine the chunk size to use for large uploads. Is this some form of static recommendation or is there some optimization being done behind the scenes?

Thank you very much in advance.
Best,
Jacob

**Comment by jgoldverg** [comment]
Hello,

This issue has been open since August 17th is there any chance this will get looked at?

Best,
Jacob

**Comment by mwwoda** [comment]
Hello @jgoldverg 

Sorry for the late response.

> A question I have is how does the current Box SDK determine the chunk size to use for large uploads

The process of uploading large files creates a so-called UploadSession before the upload begins. A call to the api is made and the API returns the number of parts to upload along with the size of each part in UploadSession. This is already an optimized value that should be used when uploading.

I would recommend using the [Upload a large file in chunks](https://github.com/box/box-java-sdk/blob/main/doc/files.md#upload-a-large-file-in-chunks) method which should handle splitting the file into chunks and checking the integrity for you.

As for specifying the chunk size in session upload, AFAIK this is not possible because the API does not consume the part_size parameter at the moment.

Thanks,
Mateusz

**Comment by jgoldverg** [comment]
Hi @mwwoda thank you very much for your response and this does explain.

A follow up question is will the Box SDK eventually support a "part_size" parameter?

Thank you,
Jacob
