### ISSUE TITLE
What is the correct usage of suppress notifications feature in Java SDK?

### ISSUE THREAD

**Issue by kmazurek93** [box/box-java-sdk#972]
- [x] I have checked that the [SDK documentation][sdk-docs] doesn't solve my issue.
- [x] I have checked that the [API documentation][api-docs] doesn't solve my issue.
- [x] I have searched the [Box Developer Forums][dev-forums] and my issue isn't already reported (or if it has been reported, I have attached a link to it, for reference).
- [x] I have searched [Issues in this repo][github-repo] and my issue isn't already reported.
- [x] I have asked assistance in Box Support, but they pointed me here.

### Description of the Issue
Hello,

I have a Box App registered with notification suppressing feature enabled. I'd like to have this working using Box Java SDK specifically on file downloads.
Unfortunately even with correct permissions I'm getting 403/401 errors. 
The sample code snippet, assuming that I have already created valid `BoxAPIConnection` object:
```
connection.suppressNotifications();
var file = new BoxFile(connection, "file_id_is_here"); //most probably 403 is returned on fetching this file data
// then download using file.getDownloadUrl()
```
I'd like to know about correct API/SDK usage, so please confirm if:

* header will work when using `new BoxFile(connection, "fileId")` or
* header will work only if we send it during the request to the URL got from BoxFile object `boxFile.getDownloadUrl()` or
* header will work only if we send it during the call of GET /files/:id/content 

It is worth mentioning, that **after** enabling required scopes, **I did a reauth to the app as an admin user**.

### Steps to Reproduce
1. Have an app with correct permissions set and suppressing notifications enabled.
2. Create proper BoxAPIConnection object.
3. Try abovementioned code snippet.

### Expected Behavior
I'd expect to not get a 403 error on creating BoxFile/downloading file.
I'd expect file to download without e-mail notification.

### Error Message, Including Stack Trace
I'm getting BoxAPIException with responseCode 403.
```
 Caused by: com.box.sdk.BoxAPIResponseException: The API returned an error code [403 | .0213727714915930b09b5704a89e3fd76] access_denied_insufficient_permissions - Access denied - insufficient permission.
 ```
### Screenshots
N/A

### Versions Used
Java SDK: 11+

[sdk-docs]: ./doc
[api-docs]: https://developer.box.com/docs
[dev-forums]: https://community.box.com/t5/Platform-and-Development-Forum/bd-p/DeveloperForum
[github-repo]: https://github.com/box/box-java-sdk/search?type=Issues

**Comment by arjankowski** [comment]
Hi @kmazurek93,

When calling `suppressNotifications()` on an instance of BoxAPIConnection you actually informing this particular connection that it should add  `Box-Notifications: off` header to all further calls on this connection.

So you need to call `connection.suppressNotifications()` before downloading a file `file.download(downloadStream);`
otherwise `Box-Notifications: off` won't be added.

But in your case you receive a  304 http status code because of lack of required scopes on your application.
Please read this article [https://developer.box.com/guides/api-calls/suppress-notifications/ ](https://developer.box.com/guides/api-calls/suppress-notifications/ )for more information
and contact support to request the required scopes.

**Comment by kmazurek93** [comment]
> I have a Box App registered with notification suppressing feature enabled

I mean, I already have required scope enabled (contacted suppor earlier, unless you've checked requestId provided and it was not enabled ATM).
So, I need to use `BoxFile#download(OutputStream downloadStream)` instead of `BoxFile#getDownloadURL()` in order to have this working, assuming scopes are enabled?
Would alternative way of calling GET request with proper header on URL fetched with `getDownloadURL()`  work?

**Comment by arjankowski** [comment]
Hi @kmazurek93,

Unfortunately but I don't see any request with requestId you mentioned.

Based on my observation I was receiving this error `access_denied_insufficient_permissions` when my app didn't have required scope for suppress notification mentioned on previous link.
When I called `BoxFile#download(OutputStream downloadStream)` after `suppressNotifications();` I received 403 status code with `access_denied_insufficient_permissions`.

But without `connection.suppressNotifications();` before downloading a file everything was OK.
So If this your case, there is still a chance that your app has insufficient scope.

Yes, you should use `BoxFile#download(OutputStream downloadStream)` method to download a file, otherwise header `Box-Notifications: off` will not be added.
Yes, an alternative way of calling GET request with proper headers (e.g. Authorization) on URL fetched with getDownloadURL() will work.

**Comment by kmazurek93** [comment]
Hi @arjankowski 
I've figured it out. 
There was additionally OAuth2 scope `manage_enterprise_properties` missing. 
However I needed to adjust download to use file.download() as you wrote or fire low-level BoxAPIRequest to get the file.

Thank you for your support, it helped much.
